mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('score.urls')),
    url(r'^', include('orders.urls')),
    url(r'^', include('products.urls')),
    url(r'^', include('contacts.urls')),
    url(r'^', include('information.urls')),
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/products/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from products import views

urlpatterns = [
    url(r'^product/(?P<product_id>\w+)/$', views.product, name='product'),
    url(r'^new_items/$', views.new_items, name='new_items'),
    url(r'^discounts/$', views.discounts, name='discounts'),
    url(r'^products_men/$', views.products_men, name='products_men'),
    url(r'^products_women/$', views.products_women, name='products_women'),
    url(r'^products_children/$', views.products_children, name='products_children'),
]

mysite/score/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from score import views

urlpatterns = [
    url(r'^score/$', views.score, name='score'),
]

mysite/products/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категория товаров'


class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    new_items = models.BooleanField(default=False)
    discount_items = models.BooleanField(default=False)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s, %s" % (self.price, self.name)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

mysite/products/forms.py
from django import forms
from . models import *

# class SubscriberForm(forms.ModelForm):
#
#     class Meta:
#         model = Subscriber
#         exclude = [""]

mysite/products/views.py
from django.shortcuts import render
from products.models import *


def product(request, product_id):
    product = Product.objects.get(id=product_id)


    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    print(request.session.session_key)


    return render(request, 'products/product.html', locals())


def discounts(request):
    products = ProductImage.objects.filter(is_active=True, product__discount_items=True, product__is_active=True)
    products_men = products.filter(product__category__id=2)
    products_women = products.filter(product__category__id=1)
    products_children = products.filter(product__category__id=3)
    return render(request, 'products/discounts.html', locals())


def new_items(request):
    products = ProductImage.objects.filter(is_active=True, product__new_items=True, product__is_active=True)
    products_men = products.filter(product__category__id=2)
    products_women = products.filter(product__category__id=1)
    products_children = products.filter(product__category__id=3)
    return render(request, 'products/discounts.html', locals())


def products_men(request):
    products = ProductImage.objects.filter(is_active=True, product__is_active=True)
    products_men = products.filter(product__category__id=2)
    return render(request, 'products/products_men.html', locals())


def products_women(request):
    products = ProductImage.objects.filter(is_active=True, product__is_active=True)
    products_women = products.filter(product__category__id=1)
    return render(request, 'products/products_women.html', locals())


def products_children(request):
    products = ProductImage.objects.filter(is_active=True, product__is_active=True)
    products_children = products.filter(product__category__id=3)
    return render(request, 'products/products_children.html', locals())

mysite/templates/products/discounts.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="section section1 men-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center" style="font-weight: bold">
                        Мужская одежда
                    </h2>
                </div>
                {% for product in products_men %}
                    {% include 'products/product_item.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="section section2 women-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center" style="font-weight: bold">
                        Женская одежда
                    </h2>
                </div>
                {% for product in products_women %}
                    {% include 'products/product_item.html' %}
                {% endfor %}

            </div>
        </div>
    </div>
    <div class="section section3 children-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center" style="font-weight: bold">
                        Детская одежда
                    </h2>
                </div>
                {% for product in products_children %}
                     {% include 'products/product_item.html' %}
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/products/product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
   <div class="container">
       <div class="row">
           <div class="col-lg-6">
               {% for image_item in product.productimage_set.all %}
                   <div class="product-image-item">
                       <img src="{{ image_item.image.url }}" class="img-responsive">
                   </div>
               {% endfor %}
           </div>
           <div class="col-lg-6">
               <h1 class="text-center">
                   {{ product.name }}
               </h1>

               {% if product.new_items == True %}
                <h2 style="color: red">
                   NEW
               </h2>
               {% endif %}

               <h3 style="color: brown">
                   Стоимость: {{ product.price }} BY
               </h3>
               <h2 style="color: white">
                   Скидка: {{ product.discount }}%
               </h2>
               <div>
                   <!-- Nav tabs -->
                   <ul class="nav nav-tabs" role="tablist">
                       <li role="presentation" class="active">
                           <a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                               Описание
                           </a>
                       </li>
                   </ul>

                    <!-- Tab panes -->
                   <div class="tab-content product-description-tabs">
                       <div role="tabpanel" class="tab-pane active" id="description">
                           <h3>{{ product.description }}</h3>
                       </div>
                   </div>
               </div>
               <div>
                   <form id="form_buying_product" class="form-inline" action="{% url 'basket_adding' %}">{% csrf_token %}
                       <div class="form-group">
                           <input type="number" class="form-control" name="number" id="number">
                       </div>

                       <div class="form-group">
                           <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                               data-product_id = "{{ product.id }}"
                               data-name = "{{ product.name }}"
                               data-price = "{{ product.price }}"
                           >
                               Добавить в корзину
                           </button>
                       </div>
                   </form>
               </div>
           </div>
       </div>
   </div>
{% endblock %}

mysite/templates/products/product_item.html
{% load static %}

{% block content %}
    <div class="col-lg-3">
        <div class="product-item">
            <div>
                <a href="{% url 'product' product.product.id %}">
                    <img src="{{ product.image.url }}" class="img-responsive your-img">
                </a>
            </div>

            {% if product.product.new_items %}
                <div class="new_items-container">
                    <span>NEW</span>
                </div>
            {% endif %}

            {% if product.product.discount %}
                <div class="discount-container">
                    <span>{{ product.product.discount }}%</span>
                </div>
            {% endif %}

            <h4 style="font-weight: bolder">{{ product.product.name }}</h4>
            <p>
                {{ product.product.description|truncatechars_html:70 }}
            </p>
            <h5 style="color: brown; font-weight: 900">{{ product.product.price }} BY</h5>
        </div>
    </div>
{% endblock %}

mysite/templates/products/products_children.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="section section1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center" style="font-weight: bold">
                        Детская одежда
                    </h2>
                </div>
                {% for product in products_children %}
                    {% include 'products/product_item.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/products/products_men.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="section section1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center" style="font-weight: bold">
                        Мужская одежда
                    </h2>
                </div>
                {% for product in products_men %}
                    {% include 'products/product_item.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/products/products_women.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="section section1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center" style="font-weight: bold">
                        Женская одежда
                    </h2>
                </div>
                {% for product in products_women %}
                    {% include 'products/product_item.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}